apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      requiredInput:
        type: number
        required: true
  
jobs:
  call_rw_1:
    uses: cb-nsrinivasa/reusable-workflow/.cloudbees/workflows/reusable.yaml
    with:
      requiredInput: ${{ inputs.requiredInput }}
    
