apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      boolInput:
        type: boolean
        

jobs:
  JobName1:
    steps:
      - name: print input
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "inputs.boolInput = ${{inputs.boolInput}}"

          

