apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        type: boolean
      tags:
        description: 'Test scenario tags'
        type: string


jobs:
  JobName1:
    steps:
      - name: print input
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo echo  The tags are ${{ inputs.tags }} ${{ inputs.logLevel }}



