apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      # choiceInput:
      #   type: choice
      #   options:
      #     - info
      #     - warning
      #     - debug
      # stringInput:
      #   type: string
      numInput:
        type: number
      boolInput:
        type: boolean  


jobs:
  JobName1:
    steps:
      - name: print input
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "inputs.numInput = ${{inputs.numInput}}"
          echo "inputs.boolInput = ${{inputs.boolInput}}"
          

