apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable wf 1

on:
  workflow_call:
    inputs:
      targetenv:
        type: string
      numTargetEnv:
        type: number
      boolTargetEnv:
        type: boolean
      choice_boolean:
        type: choice
        options:
          - info
          - warning
          - debug
      withDefault:
        type: number
        default: 10
          
        
        
      defaultTargetenv:
        type: string
        default: 'default env'
jobs:
  JobName1:
    steps:
      - name: print input
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "inputs.targetenv = ${{inputs.targetenv}}"
          echo "inputs.defaultTargetenv = ${{inputs.defaultTargetenv}}"
          echo "inputs.numTargetEnv = ${{inputs.numTargetEnv}}"
          echo "inputs.boolTargetEnv = ${{inputs.boolTargetEnv}}"
          echo "inputs.choice_boolean = ${{inputs.choice_boolean}}"
          echo "inputs.choice_boolean = ${{inputs.withDefault}}"
          
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo -n "hello" | cloudbees mask
          echo "hello world "

      - name: Say hello again
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo -n "world" | cloudbees mask
          echo "hello world"
