name: Caller Workflow

on:
  push:
    branches: [main]

jobs:
  call-reusable:
    uses: cb-nsrinivasa/reusable-workflow/.github/workflows/reusable.yaml@main
    with:
      node_version: '20'
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
