on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        type: boolean
      tags:
        description: 'Test scenario tags'
        type: string


jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} ${{ inputs.logLevel }}
