on:
  workflow_dispatch:
    inputs:
      choiceInput:
        type: choice
        options:
          - info
          - warning
          - debug
      stringInput:
        type: string
      numInput:
        type: number
      boolInput:
        type: boolean  


jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: |
          echo "inputs.choiceInput = ${{inputs.choiceInput}}"
          echo "inputs.stringInput = ${{inputs.stringInput}}"
          echo "inputs.numInput = ${{inputs.numInput}}"
          echo "inputs.boolInput = ${{inputs.boolInput}}"
