name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      input_string:
        type: string
      input_number:
        type: number
      input_boolean:
        type: boolean
      choice_boolean:
        type: choice
        options:
          - info
          - warning
          - debug

        
        
    secrets:
      MY_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secret
        run: |
          echo "input_string is ${{ inputs.input_string }}"
          echo "input_number is ${{ inputs.input_number }}"
          echo "input_boolean is ${{ inputs.input_boolean }}"
