name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      input_string:
        type: string
      input_number:
        type: number
      input_boolean:
        type: boolean        
        
    secrets:
      MY_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secret
        run: |
          echo "Secret is ${{ secrets.MY_SECRET }}"
          echo "input_string is ${{ input.input_string }}"
          echo "input_number is ${{ input.input_number }}"
          echo "input_boolean is ${{ input.input_boolean }}"
